export const SET_NOW_PLAYING_MOVIES = 'SET_NOW_PLAYING_MOVIES';
export const SET_MOVIES_LOADING = 'SET_MOVIES_LOADING';
export const SET_FAVORITE_MOVIES = 'SET_FAVORITE_MOVIES';
export const SET_SELECTED_MOVIE_DETAILS = 'SET_SELECTED_MOVIE_DETAILS';
export const SET_CAST_AND_CREW_DETAILS = 'SET_CAST_AND_CREW_DETAILS';
